skey: lim-1
pkey: p058
sname: "{Limit} 1"
sampleTex: 'lim_{x \to \infty} \frac{2x+3}{x-1} = 2'
localized:
  en: Limit 1
  ja: 極限 1
maxWidth: 165
mth:
  generators:
    z:
      expressions:
        - template: Lim (Frac (Add (Mul .a0 'x') .a1) (Add (Mul .a2 'x') .a3)) (Subscript 'x \to \infty')
          calcs: div .a0 .a2
          constraints:
            - var: a0
              min: -10
              max: 10
              excepts: 0
            - var: a1
              min: -10
              max: 10
              excepts: 0
            - var: a2
              min: -10
              max: 10
              excepts: 0
              pred: '== 1 (gcd .a0 .this)'
            - var: a3
              min: -10
              max: 10
              excepts: 0
        - template: Lim (Frac (Add .b0 (Frac .b1 'x')) (Add .b2 (Frac .b3 'x'))) (Subscript 'x \to \infty')
          calcs: div .b0 .b2
          constraints:
            - var: b0
              cal: .a0
              wrongCals: .a0; .a1; .a2; .a3; mul -1 .a0; mul -1 .a1; mul -1 .a2; mul -1 .a3; 1; 2; 3
              excepts: 0
            - var: b1
              cal: .a1
            - var: b2
              cal: .a2
              wrongCals: .a0; .a1; .a2; .a3; mul -1 .a0; mul -1 .a1; mul -1 .a2; mul -1 .a3; 1; 2; 3
              excepts: 0
            - var: b3
              cal: .a3
        - template: Frac (Add .c0 0) (Add .c1 0)
          calcs: div .c0 .c1
          constraints:
            - var: c0
              cal: .b0
              wrongCals: .b0; .b1; .b2; .b3; sub .b0 .b1; add .b1 .b3; add .b0 .b2; add .b0 .b1 .b2 .b3; 2; -2; add 1 .b2; add 1 .b3; mul -1 .b2; mul -1 .b3; add -1 .b2; add -1 .b3; 1; -1; mul -1 .b0; add .b1 .b0; .b1; mul -1 .b1; mul -1 .b0 .b1; add 1 .b0; add -1 .b0; add 2 .b0; add -2 .b0; add 1 .b1; add -1 .b1; add 2 .b1; add -2 .b1; .b2; .b3
              excepts: 0
            - var: c1
              cal: .b2
              wrongCals: .b0; .b1; .b2; .b3; sub .b0 .b1; add .b1 .b3; add .b0 .b2; add .b0 .b1 .b2 .b3; 2; -2; add 1 .b2; add 1 .b3; mul -1 .b2; mul -1 .b3; add -1 .b2; add -1 .b3; 1; -1; mul -1 .b0; add .b1 .b0; .b1; mul -1 .b1; mul -1 .b0 .b1; add 1 .b0; add -1 .b0; add 2 .b0; add -2 .b0; add 1 .b1; add -1 .b1; add 2 .b1; add -2 .b1; .b2; .b3
              excepts: 0
        - template: Frac .d0 .d1
          calcs: div .d0 .d1
          constraints:
            - var: d0
              cal: .c0
              wrongCals: .c0; .c1; mul -1 .c0; mul -1 .c1; 1; 2; 3; add .c0 .c1; sub .c0 .c1; sub .c1 .c0
              excepts: 0
            - var: d1
              cal: .c1
              wrongCals: .c0; .c1; mul -1 .c0; mul -1 .c1; 1; 2; 3; add .c0 .c1; sub .c0 .c1; sub .c1 .c0
              excepts: 0
