sampleTex: 3+8=11
mth:
  generators:
    z:
      expressions:
        - template: Add .a0 .a1
          calcs: add .a0 .a1
          constraints:
            - var: a0
              min: 2
              max: 9
            - var: a1
              min: sub 11 .a0
              max: 9
        - template: Add .b0 (WithPar (Add .b1 .b2))
          calcs: add .b0 .b1 .b2
          constraints:
            - var: b0
              cal: .a0
              wrongCals: .a0; add .a0 -1; add .a0 1; .a1; add .a1 1; add .a1 -1
            - var: b1
              cal: sub 10 .a0
              wrongCals: .a0; .a1; sub 11 .a0; sub 9 .a0
            - var: b2
              cal: sub (add .a0 .a1) 10
              wrongCals: .a0; .a1; add .a0 .a1; sub 10 .a0; sub 10 .a1; sub (add .a0 .a1) 9
        - template: Add .t0 .t1 .t2
          calcs: add .t0 .t1 .t2
          constraints:
            - var: t0
              cal: .b0
              wrongCals: .b0; .b1; .b2; add .b0 1
            - var: t1
              cal: .b1
              wrongCals: .b0; .b1; .b2; add .b1 1
            - var: t2
              cal: .b2
              wrongCals: .b0; .b1; .b2; add .b2 1
        - template: Add .c0 .c1
          calcs: add .c0 .c1
          constraints:
            - var: c0
              cal: add .t0 .t1
              wrongCals: .t0; .t1; .t2; add .t0 .t2; add .t1 .t2
            - var: c1
              cal: .t2
              wrongCals: .t0; .t1; .t2; add .t0 .t2; add .t1 .t2; add .t0 .t1
        - template: .d0
          calcs: .d0
          constraints:
            - var: d0
              cal: add .c0 .c1
              wrongCals: .c0; .c1; sub .c0 .c1; add .c0 .c1 1; add .c0 .c1 -1
    w:
      expressions:
        - template: Add .a0 .a1
          calcs: add .a0 .a1
          constraints:
            - var: a0
              min: 6
              max: 9
            - var: a1
              min: 6
              max: 9
        - template: Add (WithPar (Add .b0 .b1)) (WithPar (Add .b2 .b3))
          calcs: add .b0 .b1 .b2 .b3
          constraints:
            - var: b0
              cal: 5
              wrongCals: .a0;.a1;4;6
            - var: b1
              cal: sub .a0 5
              wrongCals: .a0; .a1; sub .a0 4; sub .a0 6
            - var: b2
              cal: 5
              wrongCals: .a0;.a1;4;6
            - var: b3
              cal: sub .a1 5
              wrongCals: .a0; .a1; sub .a0 4; sub .a0 6
        - template: Add .t0 .t1 .t2 .t3
          calcs: add .t0 .t1 .t2 .t3
          constraints:
            - var: t0
              cal: .b0
              wrongCals: .b0;.b1;.b2;.b3
            - var: t1
              cal: .b1
              wrongCals: .b0;.b1;.b2;.b3
            - var: t2
              cal: .b2
              wrongCals: .b0;.b1;.b2;.b3
            - var: t3
              cal: .b3
              wrongCals: .b0;.b1;.b2;.b3
        - template: Add .c0 .c1 .c2 .c3
          calcs: add .c0 .c1 .c2 .c3
          constraints:
            - var: c0
              cal: .t0
              wrongCals: .t0; .t1; .t2; .t3
            - var: c1
              cal: .t2
              wrongCals: .t0; .t1; .t2; .t3
            - var: c2
              cal: .t1
              wrongCals: .t0; .t1; .t2; .t3
            - var: c3
              cal: .t3
              wrongCals: .t0; .t1; .t2; .t3
        - template: Add .d0 .d1
          calcs: add .d0 .d1
          constraints:
            - var: d0
              cal: add .c0 .c1
              wrongCals: add .c0 .c2; .c0; .c1; add .c0 .c3; add .c1 .c2; add .c1 .c3; add .c2 .c3
            - var: d1
              cal: add .c2 .c3
              wrongCals: add .c0 .c2; .c0; .c1; add .c0 .c3; add .c1 .c2; add .c1 .c3; add .c0 .c1
        - template: .e0
          calcs: .e0
          constraints:
            - var: e0
              cal: add .d0 .d1
              wrongCals: .d0; .d1; add .d0 .d1 1; add .d0 .d1 -1

