sampleTex: 3+2=5
mth:
  generators:
    z:
      expressions:
        - template: Add .a0 2
          calcs: add .a0 2
          constraints:
            - var: a0
              min: 1
              max: 9
        - template: Add .b0 1 1
          calcs: add .b0 1 1
          constraints:
            - var: b0
              cal: .a0
              wrongCals: .a0; add .a0 2; add .a0 1; 0
        - template: Add .c0 1
          calcs: add .c0 1
          constraints:
            - var: c0
              cal: add .b0 1
              wrongCals: .b0; add .b0 1; add .b0 2; 0
        - template: .d0
          calcs: .d0
          constraints:
            - var: d0
              cal: add .c0 1
              wrongCals: .c0; add .c0 1; add .c0 2; 0; 1
