sampleTex: 42+9=51
mth:
  generators:
    z:
      expressions:
        - template: Add .a0 .a1
          calcs: add .a0 .a1
          constraints:
            - var: a0
              min: 11
              max: 79
              excepts: 20;30;40;50;60;70;80;90
            - var: a1
              min: 1
              max: 9
        - template: Add (WithPar (Add .b0 .b1)) .b2
          calcs: add .b0 .b1 .b2
          constraints:
            - var: b0
              cal: sub .a0 (mod .a0 10)
              wrongCals: mod .a0 10; add 10 (sub .a0 (mod .a0 10)); add -10 (sub .a0 (mod .a0 10))
            - var: b1
              cal: mod .a0 10
              wrongCals: div (sub .a0 (mod .a0 10)) 10; mod .a0 11; mod .a0 9
            - var: b2
              cal: .a1
              wrongCals: mod .a1 10; add 10 (sub .a1 (mod .a1 10)); add -10 (sub .a1 (mod .a1 10)); add 1 .a1; add 2 .a1; 1; 2; 3
        - template: Add .c0 .c1 .c2
          calcs: add .c0 .c1 .c2
          constraints:
            - var: c0
              cal: .b0
              wrongCals: .b0; .b1; .b2
            - var: c1
              cal: .b1
              wrongCals: .b0; .b1; .b2
            - var: c2
              cal: .b2
              wrongCals: .b0; .b1; .b2
        - template: Add .d0 .d1
          calcs: add .d0 .d1
          constraints:
            - var: d0
              cal: .c0
              wrongCals: .c0; .c1; .c2
            - var: d1
              cal: add .c1 .c2
              wrongCals: .c0; .c1; .c2
        - template: .e0
          calcs: .e0
          constraints:
            - var: e0
              cal: add .d0 .d1
              wrongCals: .d0; .d1; add .d0 .d1 1; add .d0 .d1 -1; add .d0 .d1 10; add .d0 .d1 20

