sampleTex: '2 \times 3 \div 3 = 2'
mth:
  generators:
    z:
      expressions:
        - template: Div (Times .a0 .a1) .a1
          calcs: div (mul .a0 .a1) .a1
          constraints:
            - var: a0
              min: 1
              max: 9
            - var: a1
              min: 1
              max: 9
        - template: .b0
          calcs: .b0
          constraints:
            - var: b0
              cal: .a0
              wrongCals: .a1; add .a0 .a1; mul .a0 .a1; add 1 .a0; add -1 .a0; 4; 7; 9
    w:
      expressions:
        - template: Times (Div .a0 .a1) .a1
          calcs: mul (div .a0 .a1) .a1
          constraints:
            - var: a0
              min: 1
              max: 9
            - var: a1
              min: 1
              max: 9
        - template: .b0
          calcs: .b0
          constraints:
            - var: b0
              cal: .a0
              wrongCals: .a1; add .a0 .a1; mul .a0 .a1; add 1 .a0; add -1 .a0; 3; 5; 7
