sampleTex: '28 \div 4 = 14 \div 2'
mth:
  generators:
    z:
      expressions:
        - template: Div .a0 .a1
          calcs: div .a0 .a1
          constraints:
            - var: h0
              min: 2
              max: 10
            - var: h1
              min: 2
              max: 5
            - var: h2
              min: 2
              max: 10
            - var: a1
              cal: mul .h1 .h2
            - var: a0
              cal: mul .h0 .h1 .h2
        - template: Div (Div .b0 .b1) (Div .b2 .b3)
          calcs: div (div .b0 .b1) (div .b2 .b3)
          constraints:
            - var: b0
              cal: .a0
              wrongCals: .a0; .a1; add 1 .h0; mul .a0 .a1; add .a0 .a1; add .h0 .a0; add .h0 .a1; .h2; mul .h1 .h2; add .h1 .h2; add .a0 .h2
            - var: b1
              cal: .h1
              wrongCals: .a0; .a1; add 1 .h0; mul .a0 .a1; add .a0 .a1; add .h0 .a0; add .h0 .a1; .h2; mul .h1 .h2; add .h1 .h2; add .a0 .h2
            - var: b2
              cal: .a1
              wrongCals: .a0; .a1; add 1 .h0; mul .a0 .a1; add .a0 .a1; add .h0 .a0; add .h0 .a1; .h2; mul .h1 .h2; add .h1 .h2; add .a0 .h2
            - var: b3
              cal: .h1
              wrongCals: .a0; .a1; add 1 .h0; mul .a0 .a1; add .a0 .a1; add .h0 .a0; add .h0 .a1; .h2; mul .h1 .h2; add .h1 .h2; add .a0 .h2
        - template: Div .c0 .c1
          calcs: div .c0 .c1
          constraints:
            - var: c0
              cal: div .b0 .b1
              wrongCals: add 1 .b1; add 1 .b0; mul .b0 .b1; add .b0 .b1; add .b1 1; .b0; .b1; .b2; .b3; add 1 (div .b0 .b1); add 1 (div .b2 .b3)
            - var: c1
              cal: div .b2 .b3
              wrongCals: add 1 .b1; add 1 .b0; mul .b0 .b1; add .b0 .b1; add .b1 1; .b0; .b1; .b2; .b3; add 1 (div .b0 .b1); add 1 (div .b2 .b3)
