sampleTex: '63 \div 3 = 21'
mth:
  generators:
    z:
      expressions:
        - template: Div .a0 .a1
          calcs: div .a0 .a1
          constraints:
            - var: h0
              min: 11
              max: 99
              excepts: 20;30;40;50;60;70;80;90
            - var: a1
              min: 1
              max: 9
            - var: a0
              cal: mul .h0 .a1
        - template: Div (Add (Times .b0 .b1) .b2) .b1
          calcs: div (add (mul .b0 .b1) .b2) .b1
          constraints:
            - var: b0
              cal: mul 10 (digit .h0 10)
              wrongCals: .a0; .a1; add 1 .h0; add -1 .h0; mul .a0 .a1; add .a0 .a1; add .h0 .a0; add .h0 .a1
            - var: b1
              cal: .a1
            - var: b2
              cal: sub .a0 (mul 10 (digit .h0 10) .a1)
              wrongCals: .h0; .a0; add 1 .a1; add -1 .a1; add .a0 .a1; add .h0 .a0; add .h0 .a1
        - template: Div (Add (Times .c0 .c1) (Times .c2 .c1) .c3) .c1
          calcs: div (add (mul .c0 .c1) (mul .c2 .c1) .c3) .c1
          constraints:
            - var: c0
              cal: .b0
              wrongCals: .b0; .b1; .b2; add .b0 .b1; add .b0 .b2; add .b1 .b2; mul .b0 .b1; mul .b0 .b2; mul .b1 .b2; mod .b2 .b1; 1; 2; 3
            - var: c1
              cal: .b1
            - var: c2
              cal: div (sub .b2 (mod .b2 .b1)) .b1
              wrongCals: .b0; .b1; .b2; add .b0 .b1; add .b0 .b2; add .b1 .b2; mul .b0 .b1; mul .b0 .b2; mul .b1 .b2; mod .b2 .b1; 1; 2; 3
            - var: c3
              cal: mod .b2 .b1
        - template: WithRemainder (Add .d0 .d1) .d2
          calcs: add .d0 .d1 (div .d2 .d3)
          constraints:
            - var: d0
              cal: .c0
              wrongCals: .c0; .c1; .c2; .c3; add .c0 .c1; add .c0 .c2; add .c0 .c3; add .c1 .c2; add .c1 .c3; add .c2 .c3; mul .c0 .c1; mul .c0 .c2; mul .c0 .c3; mul .c1 .c2; mul .c1 .c3; mul .c2 .c3; 1; 10
            - var: d1
              cal: .c2
              wrongCals: .c0; .c1; .c2; .c3; add .c0 .c1; add .c0 .c2; add .c0 .c3; add .c1 .c2; add .c1 .c3; add .c2 .c3; mul .c0 .c1; mul .c0 .c2; mul .c0 .c3; mul .c1 .c2; mul .c1 .c3; mul .c2 .c3; 1; 10
            - var: d2
              cal: .c3
              wrongCals: .c0; .c1; .c2; .c3; add .c0 .c1; add .c0 .c2; add .c0 .c3; add .c1 .c2; add .c1 .c3; add .c2 .c3; mul .c0 .c1; mul .c0 .c2; mul .c0 .c3; mul .c1 .c2; mul .c1 .c3; mul .c2 .c3; 1; 10
            - var: d3
              cal: .c1
        - template: WithRemainder .e0 .e1
          calcs: add .e0 (div .e1 .e2)
          constraints:
            - var: e0
              cal: add .d0 .d1
              wrongCals: .d1; add 1 .d0; add -1 .d0; mul .d0 .d1; add .d0 .d1; add .d1 1; add .d1 -1; 1; 10
            - var: e1
              cal: .d2
              wrongCals: .d1; add 1 .d0; add -1 .d0; mul .d0 .d1; add .d0 .d1; add .d1 1; add .d1 -1; 1; 10
            - var: e2
              cal: .d3
