- prefix: add
  name: '{Addition}'
  suffix:
    - 1
    - 2
    - 2-1
    - 2-2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
- prefix: sub
  name: '{Subtraction}'
  suffix:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 5-1
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
- prefix: mul
  name: '{Multiplication}'
  suffix:
    - 1
    - 1-1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 12
    - 13
    - 14
    - 15
- prefix: div
  name: '{Division}'
  suffix:
    - 1
    - 1-1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 9-1
    - 9-2
    - 10
    - 11
    - 12
