sampleTex: '247 \times 2 = 494'
mth:
  generators:
    z:
      expressions:
        - template: Times .a0 .a1
          calcs: mul .a0 .a1
          constraints:
            - var: a0
              min: 100
              max: 999
            - var: a1
              min: 2
              max: 9
        - template: Times (Add .b0 .b1 .b2) .b3
          calcs: mul (add .b0 .b1 .b2) .b3
          constraints:
            - var: b0
              cal: mul (digit .a0 100) 100
              wrongCals: mul (digit .a0 10) 10; mul (digit .a0 1) 10; mul (add (digit .a0 1) 1) 10; .a0; .a1; digit .a0 1; 10; 1; digit .a0 10; mul .a1 10
            - var: b1
              cal: mul 10 (digit .a0 10)
              wrongCals: sub 10 (digit .a0 10); digit .a0 10; digit .a0 1; .a1; .a0; 10; 1
            - var: b2
              cal: digit .a0 1
              wrongCals: .a0; add .a1 1; add .a1 -1; digit .a0 10; digit .a0 1
            - var: b3
              cal: .a1
              wrongCals: .a0; add .a1 1; add .a1 -1; digit .a0 10; digit .a0 1
        - template: Add .c0 .c1 .c2
          calcs: add .c0 .c1 .c2
          constraints:
            - var: c0
              cal: mul .b0 .b3
              wrongCals: 7; .b0; .b1; .b2; .b3; mul .b0 .b1; mul .b0 .b2; mul .b1 .b2; mul .b1 .b3; mul .b0 .b3; mul .b2 .b3; mul .b3 .b3
            - var: c1
              cal: mul .b1 .b3
              wrongCals: 7; .b0; .b1; .b2; .b3; mul .b0 .b1; mul .b0 .b2; mul .b1 .b2; mul .b1 .b3; mul .b0 .b3; mul .b2 .b3; mul .b3 .b3
            - var: c2
              cal: mul .b2 .b3
              wrongCals: 7; .b0; .b1; .b2; .b3; mul .b0 .b1; mul .b0 .b2; mul .b1 .b2; mul .b1 .b3; mul .b0 .b3; mul .b2 .b3; mul .b3 .b3
        - template: .d0
          calcs: .d0
          constraints:
            - var: d0
              cal: add .c0 .c1 .c2
              wrongCals: add .c0 .c1; add .c0 .c2; add .c1 .c2; add .c0 .c1 .c2 1; add .c0 .c1 .c2 10; add .c0 .c1 .c2 100; mul .c0 .c0; mul .c0 .c1; mul .c0 .c2; .c0; .c1; .c2; add .c0 .c2; add .c0 .c1; add .c1 .c2
