sampleTex: '2 \times 5 \times 7 = 70'
mth:
  generators:
    z:
      expressions:
        - template: Times .a0 .a1 .a2
          calcs: mul .a0 .a1 .a2
          constraints:
            - var: a0
              min: 1
              max: 9
            - var: a1
              min: 1
              max: 9
            - var: a2
              min: 1
              max: 9
        - template: Times .b0 .b1
          calcs: mul .b0 .b1
          constraints:
            - var: b0
              cal: mul .a0 .a1
              wrongCals: .a0; .a1; .a2; mul 2 .a0 .a1; mul .a1 .a2; mul .a0 .a2; mul 2 .a2; mul 2 .a0; mul 2 .a1; 1
            - var: b1
              cal: .a2
              wrongCals: .a0; .a1; .a2; mul 2 .a0 .a1; mul .a1 .a2; mul .a0 .a2; mul 2 .a2; mul 2 .a0; mul 2 .a1; 1
        - template: .c0
          calcs: .c0
          constraints:
            - var: c0
              cal: mul .b0 .b1
              wrongCals: .b0; .b1; mul 2 .b0 .b1; add .b0 .b1; 10; add 1 (mul .b0 .b1); add -1 (mul .b0 .b1); add 2 (mul .b0 .b1)
    w:
      expressions:
        - template: Times .a0 .a1 .a2
          calcs: mul .a0 .a1 .a2
          constraints:
            - var: a0
              min: 1
              max: 9
            - var: a1
              min: 1
              max: 9
            - var: a2
              min: 1
              max: 9
        - template: Times .t0 (Times .t1 .t2)
          calcs: mul .t0 .t1 .t2
          constraints:
            - var: t0
              cal: .a0
              wrongCals: .a0; .a1; .a2; mul 2 .a0 .a1; mul .a1 .a2; mul .a0 .a2; mul 2 .a2; mul 2 .a0; mul 2 .a1; 1
            - var: t1
              cal: .a1
              wrongCals: .a0; .a1; .a2; mul 2 .a0 .a1; mul .a1 .a2; mul .a0 .a2; mul 2 .a2; mul 2 .a0; mul 2 .a1; 1
            - var: t2
              cal: .a2
              wrongCals: .a0; .a1; .a2; mul 2 .a0 .a1; mul .a1 .a2; mul .a0 .a2; mul 2 .a2; mul 2 .a0; mul 2 .a1; 1
        - template: Times .b0 .b1
          calcs: mul .b0 .b1
          constraints:
            - var: b0
              cal: .t0
              wrongCals: .t0; .t1; .t2; mul 2 .t0 .t1; mul .t1 .t2; mul .t0 .t2; mul 2 .t2; mul 2 .t0; mul 2 .t1; 1
            - var: b1
              cal: mul .t1 .t2
              wrongCals: .t0; .t1; .t2; mul 2 .t0 .t1; mul .t1 .t2; mul .t0 .t2; mul 2 .t2; mul 2 .t0; mul 2 .t1; 1
        - template: .c0
          calcs: .c0
          constraints:
            - var: c0
              cal: mul .b0 .b1
              wrongCals: .b0; .b1; mul 2 .b0 .b1; add .b0 .b1; 10; add 1 (mul .b0 .b1); add -1 (mul .b0 .b1); add 2 (mul .b0 .b1)
