sampleTex: '20 \times 3 = 60'
mth:
  generators:
    z:
      expressions:
        - template: Times (mul .a0 10) .a1
          calcs: mul .a0 10 .a1
          constraints:
            - var: a0
              min: 2
              max: 9
            - var: a1
              min: 2
              max: 9
        - template: Times (WithPar (Times .b0 10)) .b1
          calcs: mul .b0 10 .b1
          constraints:
            - var: b0
              cal: .a0
              wrongCals: 1;10;.a1;add .a0 10; add .a0 1; add .a0 -1
            - var: b1
              cal: .a1
              wrongCals: 1;10;.a0;add .a1 10; add .a1 1; add .a1 -1
        - template: Times .c0 10 .c1
          calcs: mul .c0 10 .c1
          constraints:
            - var: c0
              cal: .b0
              wrongCals: 1;10;.b1;add .b0 10; add .b0 1; add .b0 -1
            - var: c1
              cal: .b1
              wrongCals: 1;10;.b0;add .b1 10; add .b1 1; add .b1 -1
        - template: Times .d0 .d1 10
          calcs: mul .d0 .d1 10
          constraints:
            - var: d0
              cal: .c0
              wrongCals: 1;10;.c1;add .c0 10; add .c0 1; add .c0 -1
            - var: d1
              cal: .c1
              wrongCals: 1;10;.c0;add .c1 10; add .c1 1; add .c1 -1
        - template: Times .e0 10
          calcs: mul .e0 10
          constraints:
            - var: e0
              cal: mul .d0 .d1
              wrongCals: .d0; .d1; add .d0 .d1; mul .d0 2; mul .d1 2; add (mul .d0 .d1) 1; add (mul .d0 .d1) -1; mul .d0 .d0; mul .d1 .d1
        - template: .f0
          calcs: .f0
          constraints:
            - var: f0
              cal: mul .e0 10
              wrongCals: .e0; mul .e0 2; mul .e0 3; add .e0 10; add (mul .e0 10) 10; add (mul .e0 10) -10; mul .e0 100
    w:
      expressions:
        - template: Times .a0 (mul .a1 10)
          calcs: mul .a0 .a1 10
          constraints:
            - var: a0
              min: 2
              max: 9
            - var: a1
              min: 2
              max: 9
        - template: Times .b0 (WithPar (Times .b1 10))
          calcs: mul .b0 .b1 10
          constraints:
            - var: b0
              cal: .a0
              wrongCals: 1;10;.a1;add .a0 10; add .a0 1; add .a0 -1
            - var: b1
              cal: .a1
              wrongCals: 1;10;.a0;add .a1 10; add .a1 1; add .a1 -1
        - template: Times .c0 .c1 10
          calcs: mul .c0 .c1 10
          constraints:
            - var: c0
              cal: .b0
              wrongCals: 1;10;.b1;add .b0 10; add .b0 1; add .b0 -1
            - var: c1
              cal: .b1
              wrongCals: 1;10;.b0;add .b1 10; add .b1 1; add .b1 -1
        - template: Times .e0 10
          calcs: mul .e0 10
          constraints:
            - var: e0
              cal: mul .c0 .c1
              wrongCals: .c0; .c1; add .c0 .c1; mul .c0 2; mul .c1 2; add (mul .c0 .c1) 1; add (mul .c0 .c1) -1; mul .c0 .c0; mul .c1 .c1
        - template: .f0
          calcs: .f0
          constraints:
            - var: f0
              cal: mul .e0 10
              wrongCals: .e0; mul .e0 2; mul .e0 3; add .e0 10; add (mul .e0 10) 10; add (mul .e0 10) -10; mul .e0 100
