sampleTex: '12 \times 3 = 36'
mth:
  generators:
    z:
      expressions:
        - template: Times .a0 .a1
          calcs: mul .a0 .a1
          constraints:
            - var: a0
              min: 11
              max: 99
              excepts: 20;30;40;50;60;70;80;90
            - var: a1
              min: 2
              max: 9
        - template: Times (Add .b0 .b1) .b2
          calcs: mul (add .b0 .b1) .b2
          constraints:
            - var: b0
              cal: mul (digit .a0 10) 10
              wrongCals: .a0; .a1; digit .a0 1; 10; 1; digit .a0 10; mul .a1 10
            - var: b1
              cal: digit .a0 1
              wrongCals: digit .a0 10; .a1; .a0; 10; 1
            - var: b2
              cal: .a1
              wrongCals: .a0; add .a1 1; add .a1 -1; digit .a0 10; digit .a0 1
        - template: Add (Times .c0 .c2) (Times .c1 .c3)
          calcs: add (mul .c0 .c2) (mul .c1 .c3)
          constraints:
            - var: c0
              cal: .b0
              wrongCals: .b0; .b1; .b2
            - var: c1
              cal: .b1
              wrongCals: .b0; .b1; .b2
            - var: c2
              cal: .b2
              wrongCals: .b0; .b1; .b2
            - var: c3
              cal: .b2
              wrongCals: .b0; .b1; .b2
        - template: Add .d0 .d1
          calcs: add .d0 .d1
          constraints:
            - var: d0
              cal: mul .c0 .c2
              wrongCals: mul .c0 .c1; mul .c0 .c3; .c0; .c1; .c2; .c3; add .c0 .c2
            - var: d1
              cal: mul .c1 .c3
              wrongCals: mul .c0 .c1; mul .c0 .c3; .c0; .c1; .c2; .c3; add .c1 .c3
        - template: .e0
          calcs: .e0
          constraints:
            - var: e0
              cal: add .d0 .d1
              wrongCals: .d0; .d1; mul .d0 .d1; add .d0 .d1 10; add .d0 .d1 1; add .d0 .d0; add .d1 .d1
    w:
      expressions:
        - template: Times .a0 .a1
          calcs: mul .a0 .a1
          constraints:
            - var: a0
              min: 2
              max: 9
            - var: a1
              min: 11
              max: 99
              excepts: 20;30;40;50;60;70;80;90
        - template: Times .b0 (Add .b1 .b2)
          calcs: mul .b0 (add .b1 .b2)
          constraints:
            - var: b0
              cal: .a0
              wrongCals: .a0; add .a0 1; add .a0 -1; add .a1 1; add .a1 -1; digit .a1 10; digit .a1 1
            - var: b1
              cal: mul (digit .a1 10) 10
              wrongCals: mul .a0 10; mul (add .a0 1) 10; mul (add .a0 -1) 10; add .a1 1; add .a1 -1; digit .a1 10; mul (digit .a1 1) 10
            - var: b2
              cal: digit .a1 1
              wrongCals: .a0; add .a0 1; add .a0 -1; add (digit .a1 1) 1; add (digit .a1 1) -1; digit .a1 10; digit .a1 1
        - template: Add (Times .c0 .c1) (Times .c0 .c2)
          calcs: add (mul .c0 .c1) (mul .c0 .c2)
          constraints:
            - var: c0
              cal: .b0
              wrongCals: .b0; .b1; .b2; add .b0 1; add .b0 -1; add .b1 10; add .b2 1; add .b2 -1
            - var: c1
              cal: .b1
              wrongCals: .b0; .b1; .b2; add .b0 1; add .b0 -1; add .b1 10; add .b2 1; add .b2 -1
            - var: c2
              cal: .b2
              wrongCals: .b0; .b1; .b2; add .b0 1; add .b0 -1; add .b1 10; add .b2 1; add .b2 -1
        - template: Add .d0 .d1
          calcs: add .d0 .d1
          constraints:
            - var: d0
              cal: mul .c0 .c1
              wrongCals: mul .c0 .c1; mul .c0 .c2; mul .c1 .c2; .c0; .c1; .c2; add .c0 .c2; add .c0 .c1; add .c1 .c2
            - var: d1
              cal: mul .c0 .c2
              wrongCals: mul .c0 .c1; mul .c0 .c2; mul .c1 .c2; .c0; .c1; .c2; add .c0 .c2; add .c0 .c1; add .c1 .c2
        - template: .e0
          calcs: .e0
          constraints:
            - var: e0
              cal: add .d0 .d1
              wrongCals: .d0; .d1; mul .d0 .d1; add .d0 .d1 10; add .d0 .d1 1; add .d0 .d0; add .d1 .d1
