sampleTex: '29 \times 13 = 377'
mth:
  generators:
    z:
      expressions:
        - template: Times .a0 .a1
          calcs: mul .a0 .a1
          constraints:
            - var: a0
              min: 11
              max: 99
              excepts: 20;30;40;50;60;70;80;90
            - var: a1
              min: 11
              max: 99
              excepts: 20;30;40;50;60;70;80;90
        - template: Times (Add .b0 .b1) (Add .b2 .b3)
          calcs: mul (add .b0 .b1) (add .b2 .b3)
          constraints:
            - var: b0
              cal: mul (digit .a0 10) 10
              wrongCals: mul (digit .a0 10) 10; mul (digit .a0 1) 10; mul (add (digit .a0 1) 1) 10; .a0; .a1; digit .a0 1; 10; 1; digit .a0 10; mul .a1 10
            - var: b1
              cal: digit .a0 1
              wrongCals: mul (digit .a0 10) 10; mul (digit .a0 1) 10; mul (add (digit .a0 1) 1) 10; .a0; .a1; digit .a0 1; 10; 1; digit .a0 10; mul .a1 10
            - var: b2
              cal: mul (digit .a1 10) 10
              wrongCals: mul (digit .a1 10) 10; mul (digit .a1 1) 10; mul (add (digit .a1 1) 1) 10; .a0; .a1; digit .a0 1; 10; 1; digit .a0 10; mul .a1 10
            - var: b3
              cal: digit .a1 1
              wrongCals: mul (digit .a1 10) 10; mul (digit .a1 1) 10; mul (add (digit .a1 1) 1) 10; .a0; .a1; digit .a0 1; 10; 1; digit .a0 10; mul .a1 10
        - template: Add (Times .c0 .c1) (Times .c2 .c3) (Times .c4 .c5) (Times .c6 .c7)
          calcs: add (mul .c0 .c1) (mul .c2 .c3) (mul .c4 .c5) (mul .c6 .c7)
          constraints:
            - var: c0
              cal: .b0
              wrongCals: .b0; .b1; .b2; .b3; add .b0 .b3; mul .b0 .b3; add .b0 .b1; add .b0 .b1; mul .b0 .b1; mul .b0 .b1; mul .b1 .b2; 1; 2; 3
            - var: c1
              cal: .b2
              wrongCals: .b0; .b1; .b2; .b3; add .b0 .b3; mul .b0 .b3; add .b0 .b1; add .b0 .b1; mul .b0 .b1; mul .b0 .b1; mul .b1 .b2; 1; 2; 3
            - var: c2
              cal: .b0
              wrongCals: .b0; .b1; .b2; .b3; add .b0 .b3; mul .b0 .b3; add .b0 .b1; add .b0 .b1; mul .b0 .b1; mul .b0 .b1; mul .b1 .b2; 1; 2; 3
            - var: c3
              cal: .b3
              wrongCals: .b0; .b1; .b2; .b3; add .b0 .b3; mul .b0 .b3; add .b0 .b1; add .b0 .b1; mul .b0 .b1; mul .b0 .b1; mul .b1 .b2; 1; 2; 3
            - var: c4
              cal: .b1
              wrongCals: .b0; .b1; .b2; .b3; add .b0 .b3; mul .b0 .b3; add .b0 .b1; add .b0 .b1; mul .b0 .b1; mul .b0 .b1; mul .b1 .b2; 1; 2; 3
            - var: c5
              cal: .b2
              wrongCals: .b0; .b1; .b2; .b3; add .b0 .b3; mul .b0 .b3; add .b0 .b1; add .b0 .b1; mul .b0 .b1; mul .b0 .b1; mul .b1 .b2; 1; 2; 3
            - var: c6
              cal: .b1
              wrongCals: .b0; .b1; .b2; .b3; add .b0 .b3; mul .b0 .b3; add .b0 .b1; add .b0 .b1; mul .b0 .b1; mul .b0 .b1; mul .b1 .b2; 1; 2; 3
            - var: c7
              cal: .b3
              wrongCals: .b0; .b1; .b2; .b3; add .b0 .b3; mul .b0 .b3; add .b0 .b1; add .b0 .b1; mul .b0 .b1; mul .b0 .b1; mul .b1 .b2; 1; 2; 3
        - template: Add .d0 .d1 .d2 .d3
          calcs: add .d0 .d1 .d2 .d3
          constraints:
            - var: d0
              cal: mul .c0 .c1
              wrongCals: .c0; .c1; .c2; .c3; .c4; .c5; .c6; .c7; add 1 (mul .c0 .c1); add 1 (mul .c2 .c3); add 1 (mul .c4 .c5); add 1 (mul .c6 .c7)
            - var: d1
              cal: mul .c2 .c3
              wrongCals: .c0; .c1; .c2; .c3; .c4; .c5; .c6; .c7; add 1 (mul .c0 .c1); add 1 (mul .c2 .c3); add 1 (mul .c4 .c5); add 1 (mul .c6 .c7)
            - var: d2
              cal: mul .c4 .c5
              wrongCals: .c0; .c1; .c2; .c3; .c4; .c5; .c6; .c7; add 1 (mul .c0 .c1); add 1 (mul .c2 .c3); add 1 (mul .c4 .c5); add 1 (mul .c6 .c7)
            - var: d3
              cal: mul .c6 .c7
              wrongCals: .c0; .c1; .c2; .c3; .c4; .c5; .c6; .c7; add 1 (mul .c0 .c1); add 1 (mul .c2 .c3); add 1 (mul .c4 .c5); add 1 (mul .c6 .c7)
        - template: .e0
          calcs: .e0
          constraints:
            - var: e0
              cal: add .d0 .d1 .d2 .d3
              wrongCals: .d0; .d1; add .d0 .d1 1; add .d0 .d1 -1; add .d0 .d1 10; add .d0 .d1 100; mul .d0 .d1
    w:
      expressions:
        - template: Times .a0 .a1
          calcs: mul .a0 .a1
          constraints:
            - var: a0
              min: 11
              max: 99
              excepts: 20;30;40;50;60;70;80;90
            - var: a1
              min: 11
              max: 99
              excepts: 20;30;40;50;60;70;80;90
        - template: Times .b0 (Add .b1 .b2)
          calcs: mul .b0 (add .b1 .b2)
          constraints:
            - var: b0
              cal: .a0
              wrongCals: mul (digit .a0 10) 10; mul (digit .a0 1) 10; mul (add (digit .a0 1) 1) 10; .a0; .a1; digit .a0 1; 10; 1; digit .a0 10; mul .a1 10
            - var: b1
              cal: mul (digit .a1 10) 10
              wrongCals: mul (digit .a1 10) 10; mul (digit .a1 1) 10; mul (add (digit .a1 1) 1) 10; .a0; .a1; digit .a0 1; 10; 1; digit .a0 10; mul .a1 10
            - var: b2
              cal: digit .a1 1
              wrongCals: mul (digit .a1 10) 10; mul (digit .a1 1) 10; mul (add (digit .a1 1) 1) 10; .a0; .a1; digit .a0 1; 10; 1; digit .a0 10; mul .a1 10
        - template: Add (Times .c0 .c1) (Times .c2 .c3)
          calcs: add (mul .c0 .c1) (mul .c2 .c3)
          constraints:
            - var: c0
              cal: .b0
              wrongCals: .b0; .b1; .b2; add .b0 .b1; add .b0 .b1; mul .b0 .b1; mul .b0 .b1; mul .b1 .b2; 1; 2; 3
            - var: c1
              cal: .b1
              wrongCals: .b0; .b1; .b2; add .b0 .b1; add .b0 .b1; mul .b0 .b1; mul .b0 .b1; mul .b1 .b2; 1; 2; 3
            - var: c2
              cal: .b0
              wrongCals: .b0; .b1; .b2; add .b0 .b1; add .b0 .b1; mul .b0 .b1; mul .b0 .b1; mul .b1 .b2; 1; 2; 3
            - var: c3
              cal: .b2
              wrongCals: .b0; .b1; .b2; add .b0 .b1; add .b0 .b1; mul .b0 .b1; mul .b0 .b1; mul .b1 .b2; 1; 2; 3
        - template: Add .d0 .d1
          calcs: add .d0 .d1
          constraints:
            - var: d0
              cal: mul .c0 .c1
              wrongCals: .c0; .c1; .c2; .c3; add 1 (mul .c0 .c1); add 1 (mul .c2 .c3); add .c0 .c1; add .c2 .c3
            - var: d1
              cal: mul .c2 .c3
              wrongCals: .c0; .c1; .c2; .c3; add 1 (mul .c0 .c1); add 1 (mul .c2 .c3); add .c0 .c1; add .c2 .c3
        - template: .e0
          calcs: .e0
          constraints:
            - var: e0
              cal: add .d0 .d1
              wrongCals: .d0; .d1; add .d0 .d1 1; add .d0 .d1 -1; add .d0 .d1 10; add .d0 .d1 100; mul .d0 .d1
    v:
      expressions:
        - template: Times .a0 .a1
          calcs: mul .a0 .a1
          constraints:
            - var: a0
              min: 11
              max: 99
              excepts: 20;30;40;50;60;70;80;90
            - var: a1
              min: 11
              max: 99
              excepts: 20;30;40;50;60;70;80;90
        - template: Times (Add .b0 .b1) .b2
          calcs: mul (add .b0 .b1) .b2
          constraints:
            - var: b0
              cal: mul (digit .a0 10) 10
              wrongCals: mul (digit .a0 10) 10; mul (digit .a0 1) 10; mul (add (digit .a0 1) 1) 10; .a0; .a1; digit .a0 1; 10; 1; digit .a0 10; mul .a1 10
            - var: b1
              cal: digit .a0 1
              wrongCals: mul (digit .a1 10) 10; mul (digit .a1 1) 10; mul (add (digit .a1 1) 1) 10; .a0; .a1; digit .a0 1; 10; 1; digit .a0 10; mul .a1 10
            - var: b2
              cal: .a1
              wrongCals: mul (digit .a1 10) 10; mul (digit .a1 1) 10; mul (add (digit .a1 1) 1) 10; .a0; .a1; digit .a0 1; 10; 1; digit .a0 10; mul .a1 10
        - template: Add (Times .c0 .c1) (Times .c2 .c3)
          calcs: add (mul .c0 .c1) (mul .c2 .c3)
          constraints:
            - var: c0
              cal: .b0
              wrongCals: .b0; .b1; .b2; add .b0 .b1; add .b0 .b1; mul .b0 .b1; mul .b0 .b1; mul .b1 .b2; 1; 2; 3
            - var: c1
              cal: .b2
              wrongCals: .b0; .b1; .b2; add .b0 .b1; add .b0 .b1; mul .b0 .b1; mul .b0 .b1; mul .b1 .b2; 1; 2; 3
            - var: c2
              cal: .b1
              wrongCals: .b0; .b1; .b2; add .b0 .b1; add .b0 .b1; mul .b0 .b1; mul .b0 .b1; mul .b1 .b2; 1; 2; 3
            - var: c3
              cal: .b2
              wrongCals: .b0; .b1; .b2; add .b0 .b1; add .b0 .b1; mul .b0 .b1; mul .b0 .b1; mul .b1 .b2; 1; 2; 3
        - template: Add .d0 .d1
          calcs: add .d0 .d1
          constraints:
            - var: d0
              cal: mul .c0 .c1
              wrongCals: .c0; .c1; .c2; .c3; add 1 (mul .c0 .c1); add 1 (mul .c2 .c3); add .c0 .c1; add .c2 .c3
            - var: d1
              cal: mul .c2 .c3
              wrongCals: .c0; .c1; .c2; .c3; add 1 (mul .c0 .c1); add 1 (mul .c2 .c3); add .c0 .c1; add .c2 .c3
        - template: .e0
          calcs: .e0
          constraints:
            - var: e0
              cal: add .d0 .d1
              wrongCals: .d0; .d1; add .d0 .d1 1; add .d0 .d1 -1; add .d0 .d1 10; add .d0 .d1 100; mul .d0 .d1
