sampleTex: 1000-23=977
mth:
  generators:
    z:
      expressions:
        - template: Sub .a0 .a1
          calcs: sub .a0 .a1
          constraints:
            - var: a0
              cal: 1000
            - var: a1
              min: 0
              max: 1000
        - template: .b0
          calcs: .b0
          constraints:
            - var: b0
              cal: sub .a0 .a1
              wrongCals: add 10 (sub .a0 .a1); add 1 (sub .a0 .a1); add 100 (sub .a0 .a1); add 1000 (sub .a0 .a1); add .a0 .a1; .a0; .a1; add 1 .a0 .a1; add -1 .a0 .a1; mul 10 .a1
