sampleTex: 123-5=118
mth:
  generators:
    z:
      expressions:
        - template: Sub .a0 .a1
          calcs: sub .a0 .a1
          constraints:
            - var: a0
              min: 100
              max: 999
            - var: a1
              min: 1
              max: 9
        - template: .b0
          calcs: .b0
          constraints:
            - var: b0
              cal: sub .a0 .a1
              wrongCals: sub .a0 .a1 1; sub .a0 .a1 2; add 1 .a0; add -1 .a0; .a0; .a1; add 1 .a0 .a1; add -1 .a0 .a1
