sampleTex: '0.6 \div 0.3 = 2'
mth:
  generators:
    z:
      expressions:
        - template: Div .a0 .a1
          calcs: div .a0 .a1
          constraints:
            - var: h0
              min: 1
              max: 9
            - var: h1
              choices: 10;100
            - var: h2
              min: 1
              max: 9
            - var: a0
              cal: div (mul .h0 .h2) .h1
            - var: a1
              cal: div .h2 .h1
        - template: Div (WithPar (Times .b0 .b1)) (WithPar (Times .b2 .b1))
          calcs: div (mul .b0 .b1) (mul .b2 .b1)
          constraints:
            - var: b0
              cal: mul .h0 .h2
              wrongCals: .h0; .h1; .h2; .a1; .a0; mul .h0 .a1; mul .h1 .a1; 1; 10; 0.1
            - var: b1
              cal: .h1
            - var: b2
              cal: .h2
              wrongCals: .h0; .h1; .h2; .a1; .a0; mul .h0 .a1; mul .h1 .a1; 1; 10; 0.1
        - template: Div .c0 .c1
          calcs: div .c0 .c1
          constraints:
            - var: c0
              cal: mul .b0 .b1
              wrongCals: .b0; .b1; .b2; mul 10 .b0; mul 10 .b1; mul 10 .b2
            - var: c1
              cal: mul .b2 .b1
              wrongCals: .b0; .b1; .b2; mul 10 .b0; mul 10 .b1; mul 10 .b2
        - template: .d0
          calcs: .d0
          constraints:
            - var: d0
              cal: div .c0 .c1
              wrongCals: .c0; .c1; mul .c0 .c1; add .c0 .c1; add 1 (div .c0 .c1); mul 10 (div .c0 .c1); mul 0.1 (div .c0 .c1)
