sampleTex: '0.126 + 0.02 = 0.146'
maxWidth:
mth:
  generators:
    z:
      expressions:
        - template: Add .a0 .a1
          calcs: add .a0 .a1
          constraints:
            - var: h0
              min: 1
              max: 999
            - var: h1
              min: 1
              max: 999
            - var: h2
              choices: 10;100;1000
            - var: a0
              cal: divf .h0 .h2
            - var: a1
              cal: divf .h1 .h2
        - template: .b0
          calcs: .b0
          constraints:
            - var: b0
              cal: divf (add .h0 .h1) .h2
              wrongCals: .a0; .a1; add .h0 .h1; divf (add .h0 .h1) 10; divf (add .h0 .h1) 100; divf (add .h0 .h1) 1000
    w:
      expressions:
        - template: Sub .a0 .a1
          calcs: sub .a0 .a1
          constraints:
            - var: h0
              min: 101
              max: 999
            - var: h1
              min: 1
              max: .h0
            - var: h2
              choices: 10;100;1000
            - var: a0
              cal: divf .h0 .h2
            - var: a1
              cal: divf .h1 .h2
        - template: .b0
          calcs: .b0
          constraints:
            - var: b0
              cal: divf (sub .h0 .h1) .h2
              wrongCals: .a0; .a1; add .h0 .h1; divf (add .h0 .h1) 10; divf (add .h0 .h1) 100; divf (add .h0 .h1) 1000
