sampleTex: '0.1 \times 3 = 0.3'
mth:
  generators:
    z:
      expressions:
        - template: Times .a0 .a1
          calcs: mul .a0 .a1
          constraints:
            - var: a0
              choices: 0.1;0.01
            - var: a1
              min: 1
              max: 9
        - template: .b0
          calcs: .b0
          constraints:
            - var: b0
              cal: mul .a0 .a1
              wrongCals: .a0; .a1; mul 10 .a0 .a1; mul 10 .a0; mul 10 .a1; mul 100 .a0; mul 100 .a1; mul 100 .a0 .a1; 0.1; 0.2; 0.3; 0.01; 0.02; 0.03
    w:
      expressions:
        - template: Times .a0 .a1
          calcs: mul .a0 .a1
          constraints:
            - var: a0
              min: 1
              max: 9
            - var: a1
              choices: 0.1;0.01
        - template: .b0
          calcs: .b0
          constraints:
            - var: b0
              cal: mul .a0 .a1
              wrongCals: .a0; .a1; mul 10 .a0 .a1; mul 10 .a0; mul 10 .a1; mul 100 .a0; mul 100 .a1; mul 100 .a0 .a1; 0.1; 0.2; 0.3; 0.01; 0.02; 0.03
