sampleTex: '0.3 + 0.02 + 2.1 = 2.42'
maxWidth:
mth:
  generators:
    z:
      expressions:
        - template: Add .a0 .a1 .a2
          calcs: add .a0 .a1 .a2
          constraints:
            - var: h0
              min: 1
              max: 99
            - var: h1
              min: 1
              max: 99
            - var: h2
              min: 1
              max: 99
            - var: h3
              choices: 1;10;100
            - var: h4
              choices: 1;10;100
            - var: h5
              choices: 1;10;100
            - var: a0
              cal: div .h0 .h3
            - var: a1
              cal: div .h1 .h4
            - var: a2
              cal: div .h2 .h5
        - template: Add .b0 .b1
          calcs: add .b0 .b1
          constraints:
            - var: b0
              cal: add .a0 .a1
              wrongCals: .a0; .a1; .a2; add .a0 .a1; add .a0 .a2; add .a1 .a2; mul 2 .a0; mul 2 .a1; mul 2 .a2; mul 10 .a0; mul 10 .a1; mul 10 .a2; 1; 0.1; 0.01
            - var: b1
              cal: .a2
              wrongCals: .a0; .a1; .a2; add .a0 .a1; add .a0 .a2; add .a1 .a2; mul 2 .a0; mul 2 .a1; mul 2 .a2; mul 10 .a0; mul 10 .a1; mul 10 .a2; 1; 0.1; 0.01
        - template: .c0
          calcs: .c0
          constraints:
            - var: c0
              cal: add .b0 .b1
              wrongCals: .b0; .b1; add .b0 .b1 0.1; 0.1; 0.01; mul .b0 .b1
    w:
      expressions:
        - template: Add .a0 .a1 .a2
          calcs: add .a0 .a1 .a2
          constraints:
            - var: h0
              min: 1
              max: 99
            - var: h1
              min: 1
              max: 99
            - var: h2
              min: 1
              max: 99
            - var: h3
              choices: 1;10;100
            - var: h4
              choices: 1;10;100
            - var: h5
              choices: 1;10;100
            - var: a0
              cal: div .h0 .h3
            - var: a1
              cal: div .h1 .h4
            - var: a2
              cal: div .h2 .h5
        - template: Add .b0 .b1
          calcs: add .b0 .b1
          constraints:
            - var: b0
              cal: .a0
              wrongCals: .a0; .a1; .a2; add .a0 .a1; add .a0 .a2; add .a1 .a2; mul 2 .a0; mul 2 .a1; mul 2 .a2; mul 10 .a0; mul 10 .a1; mul 10 .a2; 1; 0.1; 0.01
            - var: b1
              cal: add .a1 .a2
              wrongCals: .a0; .a1; .a2; add .a0 .a1; add .a0 .a2; add .a1 .a2; mul 2 .a0; mul 2 .a1; mul 2 .a2; mul 10 .a0; mul 10 .a1; mul 10 .a2; 1; 0.1; 0.01
        - template: .c0
          calcs: .c0
          constraints:
            - var: c0
              cal: add .b0 .b1
              wrongCals: .b0; .b1; add .b0 .b1 0.1; 0.1; 0.01; mul .b0 .b1
