sampleTex: '\frac{2}{4} = \frac{1}{2}'
mth:
  generators:
    z:
      expressions:
        - template: Frac (Raw .a0) (Raw .a1)
          calcs: div .a0 .a1
          constraints:
            - var: h0
              choices: 1;3;7;9;11
            - var: h1
              choices: 2;4;5;8;10
            - var: h2
              min: 2
              max: 10
            - var: a0
              cal: mul .h0 .h2
            - var: a1
              cal: mul .h1 .h2
        - template: Frac (Div .b0 .b2) (Div .b1 .b3)
          calcs: div (div .b0 .b2) (div .b1 .b3)
          constraints:
            - var: b0
              cal: .a0
              wrongCals: .a1; add .a0 .a1; mul .a0 .a1; .h0; mul .h0 .a0; 1; 2; 5; .h0; .h1; .h2
            - var: b1
              cal: .a1
              wrongCals: .a1; add .a0 .a1; mul .a0 .a1; .h0; mul .h0 .a0; 1; 2; 5; .h0; .h1; .h2
            - var: b2
              cal: .h2
              wrongCals: .a1; add .a0 .a1; mul .a0 .a1; .h0; mul .h0 .a0; 1; 2; 5; .h0; .h1; .h2
            - var: b3
              cal: .h2
              wrongCals: .a1; add .a0 .a1; mul .a0 .a1; .h0; mul .h0 .a0; 1; 2; 5; .h0; .h1; .h2
        - template: Frac .c0 .c1
          calcs: div .c0 .c1
          constraints:
            - var: c0
              cal: div .b0 .b2
              wrongCals: .b0; .b1; .b2; .b3; add .b0 .b1; add .b0 .b2; add .b0 .b3; mul .b0 .b1; mul .b0 .b2; add .b1 .b2; mul .b1 .b2; add 1 (div .b0 .b2); add 1 (div .b1 .b3)
            - var: c1
              cal: div .b1 .b3
              wrongCals: .b0; .b1; .b2; .b3; add .b0 .b1; add .b0 .b2; add .b0 .b3; mul .b0 .b1; mul .b0 .b2; add .b1 .b2; mul .b1 .b2; add 1 (div .b0 .b2); add 1 (div .b1 .b3)
