sampleTex: '\frac{1}{2} \div 0.1 = 5'
mth:
  generators:
    z:
      expressions:
        - template: Div (Frac .a0 .a1) .a2; Div .a2 (Frac .a0 .a1)
          calcs: div (div .a0 .a1) .a2
          constraints:
            - var: a0
              min: 1
              max: 20
            - var: a1
              min: 1
              max: 9
            - var: h0
              min: 1
              max: 9
            - var: h1
              choices: 10; 100
            - var: a2
              cal: div .h0 .h1
        - template: Div (Frac .b0 .b1) (Frac .b2 .b3); Div (Frac .b2 .b3) (Frac .b0 .b1)
          calcs: div (div .b0 .b1) (div .b2 .b3)
          constraints:
            - var: b0
              cal: .a0
              wrongCals: .a0; .a1; .a2; .h0; .h1; mul .a0 .a2; add (mul .a0 .a2) .a1 1; add (mul .a0 .a2) .a1 2; add .a0 .a1; 10; 15
            - var: b1
              cal: .a1
              wrongCals: .a0; .a1; .a2; .h0; .h1; mul .a0 .a2; add (mul .a0 .a2) .a1 1; add (mul .a0 .a2) .a1 2; add .a0 .a1; 10; 15
            - var: b2
              cal: .h0
              wrongCals: .a0; .a1; .a2; .h0; .h1; mul .a0 .a2; add (mul .a0 .a2) .a1 1; add (mul .a0 .a2) .a1 2; add .a0 .a1; 10; 15
            - var: b3
              cal: .h1
              wrongCals: .a0; .a1; .a2; .h0; .h1; mul .a0 .a2; add (mul .a0 .a2) .a1 1; add (mul .a0 .a2) .a1 2; add .a0 .a1; 10; 15
        - template: Times (Frac .c0 .c1) (Frac .c2 .c3); Times (Frac .c2 .c3) (Frac .c0 .c1)
          calcs: mul (div .c0 .c1) (div .c2 .c3)
          constraints:
            - var: c0
              cal: .b0
              wrongCals: .b0; .b1; .b2; .b0; mul .b0 .b2; add (mul .b0 .b2) .b1 1; add (mul .b0 .b2) .b1 2; add .b0 .b1; 10; 15
            - var: c1
              cal: .b1
              wrongCals: .b0; .b1; .b2; .b0; mul .b0 .b2; add (mul .b0 .b2) .b1 1; add (mul .b0 .b2) .b1 2; add .b0 .b1; 10; 15
            - var: c2
              cal: .b3
              wrongCals: .b0; .b1; .b2; .b0; mul .b0 .b2; add (mul .b0 .b2) .b1 1; add (mul .b0 .b2) .b1 2; add .b0 .b1; 10; 15
            - var: c3
              cal: .b2
              wrongCals: .b0; .b1; .b2; .b0; mul .b0 .b2; add (mul .b0 .b2) .b1 1; add (mul .b0 .b2) .b1 2; add .b0 .b1; 10; 15
        - template: Frac .d0 .d1
          calcs: div .d0 .d1
          constraints:
            - var: d0
              cal: mul .c0 .c2
              wrongCals: .c0; .c1; .c2; mul .c0 .c1; mul .c0 .c2; mul .c1 .c2; 2; 6; 8
            - var: d1
              cal: mul .c1 .c3
              wrongCals: .c0; .c1; .c2; mul .c0 .c1; mul .c0 .c2; mul .c1 .c2; 2; 6; 8
