sampleTex: '\frac{1}{2} + 0.1 = \frac{3}{5}'
mth:
  generators:
    z:
      expressions:
        - template: Add (Frac .a0 .a1) .a2; Add .a2 (Frac .a0 .a1)
          calcs: add (div .a0 .a1) .a2
          constraints:
            - var: a0
              min: 1
              max: 20
            - var: a1
              min: 1
              max: 9
            - var: h0
              min: 1
              max: 9
            - var: h1
              choices: 10
            - var: a2
              cal: div .h0 .h1
        - template: Add (Frac .b0 .b1) (Frac .b2 .b3); Add (Frac .b2 .b3) (Frac .b0 .b1)
          calcs: add (div .b0 .b1) (div .b2 .b3)
          constraints:
            - var: b0
              cal: .a0
              wrongCals: .a0; .a1; .h0; .h1; add .a0 .a1; 10; 15; 1; 2; 4
            - var: b1
              cal: .a1
              wrongCals: .a0; .a1; .h0; .h1; add .a0 .a1; 10; 15; 1; 2; 4
            - var: b2
              cal: .h0
              wrongCals: .a0; .a1; .h0; .h1; add .a0 .a1; 10; 15; 1; 2; 4
            - var: b3
              cal: .h1
              wrongCals: .a0; .a1; .h0; .h1; add .a0 .a1; 10; 15; 1; 2; 4
        - template: Add (Frac (Times .c0 .c4) (Times .c1 .c4)) (Frac (Times .c2 .c5) (Times .c3 .c5)); Add (Frac (Times .c2 .c5) (Times .c3 .c5)) (Frac (Times .c0 .c4) (Times .c1 .c4))
          calcs: add (div (mul .c0 .c4) (mul .c1 .c4)) (div (mul .c2 .c5) (mul .c3 .c5))
          constraints:
            - var: c0
              cal: .b0
              wrongCals: .b0; .b1; .b2; mul .b0 .b1; mul .b0 .b2; mul .b1 .b2; 2; 6; 8
            - var: c1
              cal: .b1
              wrongCals: .b0; .b1; .b2; mul .b0 .b1; mul .b0 .b2; mul .b1 .b2; 2; 6; 8
            - var: c2
              cal: .b2
              wrongCals: .b0; .b1; .b2; mul .b0 .b1; mul .b0 .b2; mul .b1 .b2; 2; 6; 8
            - var: c3
              cal: .b3
              wrongCals: .b0; .b1; .b2; mul .b0 .b1; mul .b0 .b2; mul .b1 .b2; 2; 6; 8
            - var: c4
              cal: div (lcm .b1 .b3) .b1
            - var: c5
              cal: div (lcm .b1 .b3) .b3
        - template: Add (Frac .d0 .d1) (Frac .d2 .d3); Add (Frac .d2 .d3) (Frac .d0 .d1)
          calcs: add (div .d0 .d1) (div .d2 .d3)
          constraints:
            - var: d0
              cal: mul .c0 .c4
              wrongCals: .c0; .c1; .c2; .c3; .c4; mul .c0 .c1; mul .c0 .c2; mul .c1 .c2; 2; 6; 8; add 1 (mul .c0 .c4); add 2 (mul .c0 .c4); add 1 (mul .c1 .c3); add 2 (mul .c1 .c3)
            - var: d1
              cal: mul .c1 .c4
              wrongCals: .c0; .c1; .c2; .c3; .c4; mul .c0 .c1; mul .c0 .c2; mul .c1 .c2; 2; 6; 8; add 1 (mul .c0 .c4); add 2 (mul .c0 .c4); add 1 (mul .c1 .c3); add 2 (mul .c1 .c3)
            - var: d2
              cal: mul .c2 .c5
              wrongCals: .c0; .c1; .c2; .c3; .c4; mul .c0 .c1; mul .c0 .c2; mul .c1 .c2; 2; 6; 8; add 1 (mul .c0 .c4); add 2 (mul .c0 .c4); add 1 (mul .c1 .c3); add 2 (mul .c1 .c3)
            - var: d3
              cal: mul .c3 .c5
              wrongCals: .c0; .c1; .c2; .c3; .c4; mul .c0 .c1; mul .c0 .c2; mul .c1 .c2; 2; 6; 8; add 1 (mul .c0 .c4); add 2 (mul .c0 .c4); add 1 (mul .c1 .c3); add 2 (mul .c1 .c3)
        - template: Frac (Raw .e0) (Raw .e1)
          calcs: div .e0 .e1
          constraints:
            - var: e0
              cal: add .d0 (div (mul .d1 .d2) .d3)
              wrongCals: .d0; .d1; .d2; .d3; add .d0 .d2 1; add .d0 .d2 2; mul .d0 .d2; mul .d1 .d3; 1; 3; 5; 10
            - var: e1
              cal: .d1
              wrongCals: .d0; .d1; .d2; .d3; add .d0 .d2 1; add .d0 .d2 2; mul .d0 .d2; mul .d1 .d3; 1; 3; 5; 10
        - template: Frac .f0 .f1
          calcs: div .f0 .f1
          constraints:
            - var: f0
              cal: .e0
              wrongCals: .e0; add 1 .e0; add 2 .e0; add -1 .e0; .e1; mul 2 .e0; mul 2 .e1; 1; 2; 4; add 1 .e1; add -1 .e1; add 2 .e1
            - var: f1
              cal: .e1
              wrongCals: .e0; add 1 .e0; add 2 .e0; add -1 .e0; .e1; mul 2 .e0; mul 2 .e1; 1; 2; 4; add 1 .e1; add -1 .e1; add 2 .e1
