- prefix: decimal
  name: '{Decimal}'
  suffix:
    - 1
    - 2
    - 2-1
    - 2-2
    - 2-3
    - 2-4
    - 2-5
    - 3
    - 3-1
    - 3-2
    - 4
    - 4-1
    - 4-2
    - 5
    - 5-1
    - 5-2
    - 6
    - 6-1
    - 6-2
- prefix: fraction
  name: '{Fraction}'
  suffix:
    - 1
    - 2
    - 2-1
    - 2-2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 11-1
    - 11-2
    - 12
    - 12-1
    - 12-2
    - 13
    - 13-1
- prefix: ratio
  name: '{Ratio}'
  suffix:
    - 1
    - 2
