sampleTex: '2:3:4 = 4:6:8'
mth:
  generators:
    z:
      expressions:
        - template: Ratio .a0 .a1 .a2
          calcs: div .a0 .a1; div .a0 .a2
          constraints:
            - var: a0
              min: 1
              max: 10
            - var: a1
              min: 1
              max: 10
            - var: a2
              min: 1
              max: 10
            - var: h0
              min: 2
              max: 10
        - template: Ratio (Times .b0 .b3) (Times .b1 .b3) (Times .b2 .b3)
          calcs: div .b0 .b1; div .b0 .b2
          constraints:
            - var: b0
              cal: .a0
              wrongCals: .a0; .a1; add 1 .a0; add 2 .a0; add 1 .a1; add 2 .a1; add .a0 .a1; mul .a0 .a1; 3; 6; 9
            - var: b1
              cal: .a1
              wrongCals: .a0; .a1; add 1 .a0; add 2 .a0; add 1 .a1; add 2 .a1; add .a0 .a1; mul .a0 .a1; 3; 6; 9
            - var: b2
              cal: .a2
              wrongCals: .a0; .a1; add 1 .a0; add 2 .a0; add 1 .a1; add 2 .a1; add .a0 .a1; mul .a0 .a1; 3; 6; 9
            - var: b3
              cal: .h0
        - template: Ratio .c0 .c1 .c2
          calcs: div .c0 .c1; div .c0 .c2
          constraints:
            - var: c0
              cal: mul .b0 .b3
              wrongCals: .b0; .b1; .b2; mul .b0 .b0; mul .b2 .b2; mul .b1 .b1; add 1 .b0; add 2 .b0; add 1 .b1; add 2 .b1; add .b0 .b1; mul .b0 .b1; 3; 6; 9
            - var: c1
              cal: mul .b1 .b3
              wrongCals: .b0; .b1; .b2; mul .b0 .b0; mul .b2 .b2; mul .b1 .b1; add 1 .b0; add 2 .b0; add 1 .b1; add 2 .b1; add .b0 .b1; mul .b0 .b1; 3; 6; 9
            - var: c2
              cal: mul .b2 .b3
              wrongCals: .b0; .b1; .b2; mul .b0 .b0; mul .b2 .b2; mul .b1 .b1; add 1 .b0; add 2 .b0; add 1 .b1; add 2 .b1; add .b0 .b1; mul .b0 .b1; 3; 6; 9
    w:
      expressions:
        - template: Ratio .a0 .a1 .a2
          calcs: div .a0 .a1; div .a0 .a2
          constraints:
            - var: h0
              min: 1
              max: 10
            - var: h1
              min: 1
              max: 10
            - var: h2
              min: 1
              max: 10
            - var: h3
              min: 2
              max: 10
            - var: a0
              cal: mul .h0 .h3
            - var: a1
              cal: mul .h1 .h3
            - var: a2
              cal: mul .h2 .h3
        - template: Ratio (Div .b0 .b3) (Div .b1 .b3) (Div .b2 .b3)
          calcs: div .b0 .b1; div .b0 .b2
          constraints:
            - var: b0
              cal: .a0
              wrongCals: .a0; .a1; add 1 .a0; add 2 .a0; add 1 .a1; add 2 .a1; add .a0 .a1; mul .a0 .a1; 3; 6; 9
            - var: b1
              cal: .a1
              wrongCals: .a0; .a1; add 1 .a0; add 2 .a0; add 1 .a1; add 2 .a1; add .a0 .a1; mul .a0 .a1; 3; 6; 9
            - var: b2
              cal: .a2
              wrongCals: .a0; .a1; add 1 .a0; add 2 .a0; add 1 .a1; add 2 .a1; add .a0 .a1; mul .a0 .a1; 3; 6; 9
            - var: b3
              cal: .h2
        - template: Ratio .c0 .c1 .c2
          calcs: div .c0 .c1; div .c0 .c2
          constraints:
            - var: c0
              cal: div .b0 .b3
              wrongCals: .b0; .b1; .b2; mul .b0 .b0; mul .b2 .b2; mul .b1 .b1; add 1 .b0; add 2 .b0; add 1 .b1; add 2 .b1; add .b0 .b1; mul .b0 .b1; 3; 6; 9
            - var: c1
              cal: div .b1 .b3
              wrongCals: .b0; .b1; .b2; mul .b0 .b0; mul .b2 .b2; mul .b1 .b1; add 1 .b0; add 2 .b0; add 1 .b1; add 2 .b1; add .b0 .b1; mul .b0 .b1; 3; 6; 9
            - var: c2
              cal: div .b2 .b3
              wrongCals: .b0; .b1; .b2; mul .b0 .b0; mul .b2 .b2; mul .b1 .b1; add 1 .b0; add 2 .b0; add 1 .b1; add 2 .b1; add .b0 .b1; mul .b0 .b1; 3; 6; 9
