skey: sub-4
pkey: p026
sname: "{Subtraction} 5"
sampleTex: 32-4=28
maxWidth: 148
mth:
  generators:
    z:
      expressions:
        - template: Sub .a0 .a1
          calcs: sub .a0 .a1
          constraints:
            - var: a0
              min: 11
              max: 98
              excepts: 19;29;39;49;59;69;79;89
            - var: a1
              min: max 1 (sub (digit .a0 1) 9)
              max: 9
        - template: Sub (WithPar (Add .b0 10)) .b1
          calcs: sub (add .b0 10) .b1
          constraints:
            - var: b0
              cal: sub .a0 10
              wrongCals: .a0; .a1; sub .a0 1; sub .a0 20; mul 10 (digit .a0 10); sub .a0 9
            - var: b1
              cal: .a1
              wrongCals: .a0; add .a1 1; add .a1 -1; sub .a0 10
        - template: Add .c0 (Sub 10 .c1)
          calcs: add .c0 (sub 10 .c1)
          constraints:
            - var: c0
              cal: .b0
              wrongCals: add .b0 10; add .b0 1; .b1
            - var: c1
              cal: .b1
              wrongCals: .b0; add .b1 1
        - template: Add .d0 .d1
          calcs: add .d0 .d1
          constraints:
            - var: d0
              cal: .c0
              wrongCals: add .c0 10; add .c0 1; .c1
            - var: d1
              cal: sub 10 .c1
              wrongCals: .c0; add .c1 1; sub 11 .c1; sub 9 .c1; digit .c0 1; digit .c0 10
        - template: .e0
          calcs: .e0
          constraints:
            - var: e0
              cal: add .d0 .d1
              wrongCals: .d0; .d1; add .d0 .d0; add .d1 .d1; sub .d0 .d1
