sampleTex: '\frac{x+3}{2} \times (-4) = -2x-6'
mth:
  generators:
    z:
      expressions:
        - template: Times (Frac (Add (Mul .a0 'x') .a1) .a2) .a3
          calcs: mul (div .a0 .a2) .a3; mul (div .a1 .a2) .a3
          constraints:
            - var: h0
              min: 2
              max: 5
              excepts: 0;1
            - var: a0
              min: -15
              max: 15
              excepts: 0
            - var: a1
              min: -15
              max: 15
              excepts: 0
            - var: a2
              min: -5
              max: 5
              excepts: 0
            - var: a3
              cal: mul .h0 .a2
        - template: Times (Add (Mul .b0 'x') .b1) .b2
          calcs: mul .b0 .b2; mul .b1 .b2
          wrongCals: add 1 $cal; add 2 $cal; add -1 $cal; add -2 $cal; $vars; mul -1 $vars; 1; 2; 3
          constraints:
            - var: b0
              cal: .a0
              excepts: 0
            - var: b1
              cal: .a1
              excepts: 0
            - var: b2
              cal: .h0
              excepts: 0
        - template: Add (Mul .c0 'x') .c1
          calcs: .c0; .c1
          wrongCals: add 1 $cal; add 2 $cal; add -1 $cal; add -2 $cal; $vars; mul -1 $vars; 1; 2; 3
          constraints:
            - var: c0
              cal: mul .b0 .b2
            - var: c1
              cal: mul .b1 .b2
