sampleTex: '-24x \div 8 = -3x'
mth:
  generators:
    z:
      expressions:
        - template: Div (Mul .a0 'x') .a1
          calcs: div .a0 .a1
          constraints:
            - var: h0
              min: -4
              max: 4
              excepts: 0
            - var: a1
              min: -15
              max: 15
              excepts: 0
            - var: a0
              cal: mul .h0 .a1
        - template: Mul (Div .b0 .b1) 'x'
          calcs: div .b0 .b1
          wrongCals: add 1 $cal; add 2 $cal; add -1 $cal; add -2 $cal; $vars; mul -1 $vars; 1; 2; 3
          constraints:
            - var: b0
              cal: .a0
              excepts: 0
            - var: b1
              cal: .a1
              excepts: 0
        - template: Mul .c0 'x'
          calcs: .c0
          wrongCals: add 1 $cal; add 2 $cal; add -1 $cal; add -2 $cal; $vars; mul -1 $vars; 1; 2; 3
          constraints:
            - var: c0
              cal: div .b0 .b1
    w:
      expressions:
        - template: Div (Mul .a0 'x') .a1
          calcs: div .a0 .a1
          constraints:
            - var: a0
              min: -50
              max: 50
              excepts: 0
            - var: a1
              min: -15
              max: 15
              excepts: 0
        - template: Mul (Div .b0 .b1) 'x'
          calcs: div .b0 .b1
          wrongCals: add 1 $cal; add 2 $cal; add -1 $cal; add -2 $cal; $vars; mul -1 $vars; 1; 2; 3
          constraints:
            - var: b0
              cal: .a0
              excepts: 0
            - var: b1
              cal: .a1
              excepts: 0
        - template: Mul (Frac .c0 .c1) 'x'
          calcs: div .c0 .c1
          wrongCals: add 1 $cal; add 2 $cal; add -1 $cal; add -2 $cal; $vars; mul -1 $vars; 1; 2; 3
          constraints:
            - var: c0
              cal: .b0
              excepts: 0
            - var: c1
              cal: .b1
              excepts: 0
    u:
      expressions:
        - template: Div (Add (Mul .a0 'x') .a1) .a2
          calcs: div .a0 .a2; div .a1 .a2
          constraints:
            - var: h0
              min: -4
              max: 4
              excepts: 0
            - var: h1
              min: -8
              max: 8
              excepts: 0
            - var: a2
              min: -10
              max: 10
              excepts: 0
            - var: a0
              cal: mul .h0 .a2
            - var: a1
              cal: mul .h1 .a2
        - template: Add (Mul (Div .b0 .b2) 'x') (Div .b1 .b3)
          calcs: div .b0 .b2; div .b1 .b3
          wrongCals: add 1 $cal; add 2 $cal; add -1 $cal; add -2 $cal; $vars; mul -1 $vars; 1; 2; 3
          constraints:
            - var: b0
              cal: .a0
              excepts: 0
            - var: b1
              cal: .a1
              excepts: 0
            - var: b2
              cal: .a2
              excepts: 0
            - var: b3
              cal: .a2
              excepts: 0
        - template: Add (Mul .c0 'x') .c1
          calcs: .c0; .c1
          wrongCals: add 1 $cal; add 2 $cal; add -1 $cal; add -2 $cal; $vars; mul -1 $vars; 1; 2; 3
          constraints:
            - var: c0
              cal: div .b0 .b2
            - var: c1
              cal: div .b1 .b3
    v:
      expressions:
        - template: Div (Add (Mul .a0 'x') .a1) .a2
          calcs: div .a0 .a2; div .a1 .a2
          constraints:
            - var: h0
              min: -4
              max: 4
              excepts: 0
            - var: h1
              min: -8
              max: 8
              excepts: 0
            - var: a2
              min: -10
              max: 10
              excepts: 0
            - var: a0
              cal: mul .h0 .a2
            - var: a1
              cal: mul .h1 .a2
        - template: Add (Mul (Div .b0 .b2) 'x') (Div .b1 .b3)
          calcs: div .b0 .b2; div .b1 .b3
          wrongCals: add 1 $cal; add 2 $cal; add -1 $cal; add -2 $cal; $vars; mul -1 $vars; 1; 2; 3
          constraints:
            - var: b0
              cal: .a0
              excepts: 0
            - var: b1
              cal: .a1
              excepts: 0
            - var: b2
              cal: .a2
              excepts: 0
            - var: b3
              cal: .a2
              excepts: 0
        - template: Add (Mul .c0 'x') .c1
          calcs: .c0; .c1
          wrongCals: add 1 $cal; add 2 $cal; add -1 $cal; add -2 $cal; $vars; mul -1 $vars; 1; 2; 3
          constraints:
            - var: c0
              cal: div .b0 .b2
            - var: c1
              cal: div .b1 .b3
    p:
      expressions:
        - template: Div (Add (Mul .a0 'x') .a1) .a2
          calcs: div .a0 .a2; div .a1 .a2
          constraints:
            - var: a0
              min: -20
              max: 20
              excepts: 0
            - var: a1
              min: -20
              max: 20
              excepts: 0
            - var: a2
              min: -10
              max: 10
              excepts: 0
        - template: Add (Mul (Div .b0 .b2) 'x') (Div .b1 .b3)
          calcs: div .b0 .b2; div .b1 .b3
          wrongCals: add 1 $cal; add 2 $cal; add -1 $cal; add -2 $cal; $vars; mul -1 $vars; 1; 2; 3
          constraints:
            - var: b0
              cal: .a0
              excepts: 0
            - var: b1
              cal: .a1
              excepts: 0
            - var: b2
              cal: .a2
              excepts: 0
            - var: b3
              cal: .a2
              excepts: 0
        - template: Add (Mul (Frac .c0 .c2) 'x') (Frac .c1 .c3)
          calcs: div .c0 .c2; div .c1 .c3
          wrongCals: add 1 $cal; add 2 $cal; add -1 $cal; add -2 $cal; $vars; mul -1 $vars; 1; 2; 3
          constraints:
            - var: c0
              cal: .b0
            - var: c1
              cal: .b1
            - var: c2
              cal: .b2
            - var: c3
              cal: .b3
