sampleTex: '2.3 \times (-2) - (-3) \times 1.2 = -1'
mth:
  generators:
    z:
      expressions:
        - template: Add (Times .a0 .a1) (Times .a2 .a3)
          calcs: add (mul .a0 .a1) (mul .a2 .a3)
          constraints:
            - var: t0
              min: -30
              max: 5
            - var: t1
              min: -10
              max: 10
            - var: t2
              min: -10
              max: 10
            - var: t3
              min: -5
              max: 30
            - var: h0
              choices: 1;10
            - var: h1
              choices: 1;10
            - var: h2
              choices: 1;10
            - var: h3
              choices: 1;10
            - var: a0
              cal: div .t0 .h0
            - var: a1
              cal: div .t1 .h1
            - var: a2
              cal: div .t2 .h2
            - var: a3
              cal: div .t3 .h3
        - template: Add .b0 .b1
          calcs: add .b0 .b1
          constraints:
            - var: b0
              cal: mul .a0 .a1
              wrongCals: .a0; .a1; .a2; .a3; add .a1 .a2; mul -1 .a0 .a1; 1; -1
            - var: b1
              cal: mul .a2 .a3
              wrongCals: .a0; .a1; .a2; .a3; add .a1 .a2; mul -1 .a0 .a1; 1; -1
        - template: .c0
          calcs: .c0
          constraints:
            - var: c0
              cal: add .b0 .b1
              wrongCals: .b0; .b1; add .b0 .b1; sub .b0 .b1; sub .b1 .b0; mul .b0 .b1; 1; -1
    w:
      expressions:
        - template: Sub (Times .a0 .a1) (Times .a2 .a3)
          calcs: sub (mul .a0 .a1) (mul .a2 .a3)
          constraints:
            - var: t0
              min: -30
              max: 5
            - var: t1
              min: -10
              max: 10
            - var: t2
              min: -10
              max: 10
            - var: t3
              min: -5
              max: 30
            - var: h0
              choices: 1;10
            - var: h1
              choices: 1;10
            - var: h2
              choices: 1;10
            - var: h3
              choices: 1;10
            - var: a0
              cal: div .t0 .h0
            - var: a1
              cal: div .t1 .h1
            - var: a2
              cal: div .t2 .h2
            - var: a3
              cal: div .t3 .h3
        - template: Add .b0 .b1
          calcs: add .b0 .b1
          constraints:
            - var: b0
              cal: mul .a0 .a1
              wrongCals: .a0; .a1; .a2; .a3; add .a1 .a2; mul -1 .a0 .a1; 1; -1
            - var: b1
              cal: mul -1 .a2 .a3
              wrongCals: .a0; .a1; .a2; .a3; add .a1 .a2; mul -1 .a0 .a1; 1; -1
        - template: .c0
          calcs: .c0
          constraints:
            - var: c0
              cal: add .b0 .b1
              wrongCals: .b0; .b1; add .b0 .b1; sub .b0 .b1; sub .b1 .b0; mul .b0 .b1; 1; -1
