sampleTex: '(-\frac{2}{3})^{2} = \frac{4}{9}'
mth:
  generators:
    z:
      expressions:
        - template: Pow (Frac .a0 .a1) .a2
          calcs: pow (div .a0 .a1) .a2
          constraints:
            - var: a0
              min: -9
              max: 9
              excepts: 0
            - var: a1
              min: -9
              max: 9
              excepts: 0; .a0; mul -1 .a0
            - var: a2
              min: 1
              max: 3
        - template: Times (* .b2 (Frac .b0 .b1))
          calcs: pow (div .b0 .b1) .b2
          ignore: '&& (== 0 (mod .a2 2)) (== 0 (add (div .b0 .b1) (div .a0 .a1)))'
          constraints:
            - var: b0
              cal: .a0
              wrongCals: add 1 $cal; add -1 $cal; mul -1 .a0; add .a1 .a0; .a1; mul -1 .a1; mul -1 .a0 .a1; add 1 .a0; add -1 .a0; add 2 .a0; add -2 .a0; add 1 .a1; add -1 .a1; add 2 .a1; add -2 .a1
            - var: b1
              cal: .a1
              wrongCals: add 1 $cal; add -1 $cal; mul -1 .a0; add .a1 .a0; .a1; mul -1 .a1; mul -1 .a0 .a1; add 1 .a0; add -1 .a0; add 2 .a0; add -2 .a0; add 1 .a1; add -1 .a1; add 2 .a1; add -2 .a1
            - var: b2
              cal: .a2
              min: 1
              max: 4
              wrongCals: 1;2;3;4
        - template: Frac .c0 .c1
          calcs: div .c0 .c1
          constraints:
            - var: c0
              cal: pow .b0 .b2
              wrongCals: add -1 (pow .b0 .b2); add 1 (pow .b0 .b2); mul -1 (pow .b0 .b2); .b0; .b2; add .b0 .b2; sub .b0 .b2; sub .b2 .b0; mul .b0 .b2
            - var: c1
              cal: pow .b1 .b2
              wrongCals: add -1 (pow .b1 .b2); add 1 (pow .b1 .b2); mul -1 (pow .b1 .b2); .b1; .b2; add .b1 .b2; sub .b1 .b2; sub .b2 .b1; mul .b1 .b2
