sampleTex: '\frac{2}{3} \times (-\frac{3}{4}) + (-2) \times \frac{1}{4} = -1'
mth:
  generators:
    z:
      expressions:
        - template: Add (Times (Frac .a0 .a1) (Frac .a2 .a3)) (Times (Frac .a4 .a5) (Frac .a6 .a7))
          calcs: add (mul (div .a0 .a1) (div .a2 .a3)) (mul (div .a4 .a5) (div .a6 .a7))
          ignore: '== 0 (add (mul (div .a0 .a1) (div .a2 .a3)) (mul (div .a4 .a5) (div .a6 .a7)))'
          constraints:
            - var: a0
              min: -10
              max: 10
              excepts: 0
            - var: a1
              min: -10
              max: 10
              excepts: 0
              pred: '_|_ .a0 .this'
            - var: a2
              min: -10
              max: 10
              excepts: 0
            - var: a3
              min: -10
              max: 10
              excepts: 0
              pred: '_|_ .a2 .this'
            - var: a4
              min: -10
              max: 10
              excepts: 0
            - var: a5
              min: -10
              max: 10
              excepts: 0
              pred: '_|_ .a4 .this'
            - var: a6
              min: -10
              max: 10
              excepts: 0
            - var: a7
              min: -10
              max: 10
              excepts: 0
              pred: '_|_ .a6 .this'
        - template: Add (Frac .b0 .b1) (Frac .b2 .b3)
          calcs: add (div .b0 .b1) (div .b2 .b3)
          constraints:
            - var: b0
              cal: mul .a0 .a2
              wrongCals: .a0; .a1; .a2; .a3; .a4; .a5; .a6; .a7; add .a1 .a2; mul -1 .a0 .a2; 1; -1; mul -1 .a1 .a3; mul -1 .a4 .a6; mul -1 .a5 .a7
            - var: b1
              cal: mul .a1 .a3
              wrongCals: .a0; .a1; .a2; .a3; .a4; .a5; .a6; .a7; add .a1 .a2; mul -1 .a0 .a2; 1; -1; mul -1 .a1 .a3; mul -1 .a4 .a6; mul -1 .a5 .a7
            - var: b2
              cal: mul .a4 .a6
              wrongCals: .a0; .a1; .a2; .a3; .a4; .a5; .a6; .a7; add .a1 .a2; mul -1 .a0 .a2; 1; -1; mul -1 .a1 .a3; mul -1 .a4 .a6; mul -1 .a5 .a7
            - var: b3
              cal: mul .a5 .a7
              wrongCals: .a0; .a1; .a2; .a3; .a4; .a5; .a6; .a7; add .a1 .a2; mul -1 .a0 .a2; 1; -1; mul -1 .a1 .a3; mul -1 .a4 .a6; mul -1 .a5 .a7
        - template: Frac .c0 .c1
          calcs: div .c0 .c1
          constraints:
            - var: c0
              cal: add (mul .b0 .b3) (mul .b1 .b2)
              wrongCals: .b0; .b1; add .b0 .b1; sub .b0 .b1; sub .b1 .b0; mul .b0 .b1; 1; -1
            - var: c1
              cal: mul .b1 .b3
              wrongCals: .b0; .b1; add .b0 .b1; sub .b0 .b1; sub .b1 .b0; mul .b0 .b1; 1; -1
    w:
      expressions:
        - template: Sub (Times (Frac .a0 .a1) (Frac .a2 .a3)) (Times (Frac .a4 .a5) (Frac .a6 .a7))
          calcs: sub (mul (div .a0 .a1) (div .a2 .a3)) (mul (div .a4 .a5) (div .a6 .a7))
          ignore: '== 0 (sub (mul (div .a0 .a1) (div .a2 .a3)) (mul (div .a4 .a5) (div .a6 .a7)))'
          constraints:
            - var: a0
              min: -10
              max: 10
              excepts: 0
            - var: a1
              min: -10
              max: 10
              excepts: 0
            - var: a2
              min: -10
              max: 10
              excepts: 0
            - var: a3
              min: -10
              max: 10
              excepts: 0
            - var: a4
              min: -10
              max: 10
              excepts: 0
            - var: a5
              min: -10
              max: 10
              excepts: 0
            - var: a6
              min: -10
              max: 10
              excepts: 0
            - var: a7
              min: -10
              max: 10
              excepts: 0
        - template: Add (Frac .b0 .b1) (Frac .b2 .b3)
          calcs: add (div .b0 .b1) (div .b2 .b3)
          constraints:
            - var: b0
              cal: mul .a0 .a2
              wrongCals: .a0; .a1; .a2; .a3; .a4; .a5; .a6; .a7; add .a1 .a2; mul -1 .a0 .a2; 1; -1; mul -1 .a1 .a3; mul -1 .a4 .a6; mul -1 .a5 .a7
            - var: b1
              cal: mul .a1 .a3
              wrongCals: .a0; .a1; .a2; .a3; .a4; .a5; .a6; .a7; add .a1 .a2; mul -1 .a0 .a2; 1; -1; mul -1 .a1 .a3; mul -1 .a4 .a6; mul -1 .a5 .a7
            - var: b2
              cal: mul -1 .a4 .a6
              wrongCals: .a0; .a1; .a2; .a3; .a4; .a5; .a6; .a7; add .a1 .a2; mul -1 .a0 .a2; 1; -1; mul -1 .a1 .a3; mul -1 .a4 .a6; mul -1 .a5 .a7
            - var: b3
              cal: mul .a5 .a7
              wrongCals: .a0; .a1; .a2; .a3; .a4; .a5; .a6; .a7; add .a1 .a2; mul -1 .a0 .a2; 1; -1; mul -1 .a1 .a3; mul -1 .a4 .a6; mul -1 .a5 .a7
        - template: Frac .c0 .c1
          calcs: div .c0 .c1
          constraints:
            - var: c0
              cal: add (mul .b0 .b3) (mul .b1 .b2)
              wrongCals: .b0; .b1; add .b0 .b1; sub .b0 .b1; sub .b1 .b0; mul .b0 .b1; 1; -1
            - var: c1
              cal: mul .b1 .b3
              wrongCals: .b0; .b1; add .b0 .b1; sub .b0 .b1; sub .b1 .b0; mul .b0 .b1; 1; -1
